### ISSUE TITLE
Consul provider times out occasionally

### ISSUE THREAD

**Issue by webdog** [pcmccarron/hcp-eks-ecs-ap#1]
│ Error: Get "https://server-5avnim.consul.5939a5d7-821b-414b-bf1d-53fdcf8748bf.aws.hashicorp.cloud/v1/catalog/service/product-api?dc=consul&stale=&wait=60000ms": dial tcp: lookup server-5aVNim.consul.5939a5d7-821b-414b-bf1d-53fdcf8748bf.aws.hashicorp.cloud on 75.75.75.75:53: no such host
│
│  with data.consul_service.each["product-api"],
│  on ecs-data.tf line 15, in data "consul_service" "each":
│  15: data "consul_service" "each" {
│
╵
╷
│ Error: Get "https://server-5avnim.consul.5939a5d7-821b-414b-bf1d-53fdcf8748bf.aws.hashicorp.cloud/v1/catalog/service/postgres?dc=consul&stale=&wait=60000ms": dial tcp: lookup server-5aVNim.consul.5939a5d7-821b-414b-bf1d-53fdcf8748bf.aws.hashicorp.cloud on 75.75.75.75:53: no such host
│
│  with data.consul_service.each["postgres"],
│  on ecs-data.tf line 15, in data "consul_service" "each":
│  15: data "consul_service" "each" {

This happens because the `consul_service_` resources are attempting to call back to HCP Consul, but the hostname hasn't propagated to the the user's local DNS, and fails because the DNS provider can't resolve the hostname.

**Comment by webdog** [comment]
I think there are two resolution paths here:

* Use the terraform [DNS provider](https://registry.terraform.io/providers/hashicorp/dns/latest/docs)'s [dns_a_record_set](https://registry.terraform.io/providers/hashicorp/dns/latest/docs/data-sources/dns_a_record_set) data source to create a queryable resource that blocks progress of the terraform project until it evaluates the hostname successfully.

* Run the code on terraform cloud. Since TFC *probably* has direct/better peering to AWS, theoretically the DNS propagation should be faster. But that still runs the risk of the lookup failing.

I'm going to take a look and will submit a PR to patch this issue.

**Comment by pcmccarron** [comment]
@webdog, just a heads up. This may not be the same issue you faced previously. @vanphan24 removed the Consul provider for the `providers.tf`, but the error persisted. This may be a case of there needing to be a dependency on the Consul cluster being deployed in order for that resource block to work properly. For now, I'm going to add a `depends_on` in the code and we can work through your fix in the future.
